name: CI
# Controles de evento para execução
on:
  # Atualização na branch “QA” por push ou pull-request
  push:
    branches: [ "QA" ]
  pull_request:
    branches: [ "main" ]
# JOBS de atividade
jobs:
  # Task com nome BUILD
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Run a one-line script
        run: echo Hello, world!
      - name: Run a one-line script
        run: echo Usando a Branch de QA
